"""
Netch 2 - Compile to EXE
Uses PyInstaller to bundle a .ntch script + interpreter into a standalone .exe
No Python required to run the compiled app.
"""
import sys, os, subprocess, shutil, tempfile, argparse

NETCH_DIR    = os.path.join(os.path.expanduser("~"), "Netch2")
INTERPRETER  = os.path.join(NETCH_DIR, "interpreter.py")

def banner():
    print("\n" + "═"*50)
    print("  🔨  Netch 2 — Compile to EXE")
    print("  An Aerotion Production")
    print("═"*50 + "\n")

def compile_to_exe(ntch_path, output_dir=None, app_name=None, icon=None, onefile=True):
    banner()

    if not os.path.exists(ntch_path):
        print(f"  ❌  File not found: {ntch_path}")
        sys.exit(1)

    if not os.path.exists(INTERPRETER):
        print(f"  ❌  interpreter.py not found at: {INTERPRETER}")
        print("  Make sure Netch 2 is installed properly.")
        sys.exit(1)

    abs_ntch = os.path.abspath(ntch_path)
    app_name = app_name or os.path.splitext(os.path.basename(ntch_path))[0]
    out_dir  = output_dir or os.path.join(os.path.dirname(abs_ntch), "dist")

    print(f"  📄  Script:   {abs_ntch}")
    print(f"  📦  App name: {app_name}")
    print(f"  📁  Output:   {out_dir}")
    print()

    # check pyinstaller
    try:
        import PyInstaller
        print(f"  ✅  PyInstaller {PyInstaller.__version__} found")
    except ImportError:
        print("  📥  Installing PyInstaller...")
        subprocess.check_call([sys.executable, "-m", "pip", "install",
                               "pyinstaller", "--break-system-packages", "-q"])
        print("  ✅  PyInstaller installed")

    # build a launcher script that bundles the .ntch content
    print("\n  ⚙️   Preparing launcher...")
    tmp_dir = tempfile.mkdtemp()

    with open(abs_ntch, 'r', encoding='utf-8') as f:
        ntch_content = f.read()

    # escape for embedding in Python string
    ntch_escaped = ntch_content.replace('\\', '\\\\').replace('"""', '\\"\\"\\"')

    launcher_src = f'''#!/usr/bin/env python3
# Netch 2 compiled app — generated by netch compile
import sys, os, tempfile, tkinter

NTCH_SOURCE = """{ntch_escaped}"""

def main():
    # write the .ntch to a temp file and run it
    tmp = tempfile.NamedTemporaryFile(suffix=".ntch", delete=False,
                                      mode="w", encoding="utf-8")
    tmp.write(NTCH_SOURCE)
    tmp.close()

    # import and run the interpreter inline
    import importlib.util, types

    # patch sys.argv for the interpreter
    sys.argv = ["netch", tmp.name]

    # load interpreter
    interp_path = os.path.join(os.path.dirname(sys.executable), "interpreter.py")
    if not os.path.exists(interp_path):
        # try next to the exe
        interp_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "interpreter.py")

    if os.path.exists(interp_path):
        spec = importlib.util.spec_from_file_location("netch_interp", interp_path)
        mod  = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        mod.run_file(tmp.name)
    else:
        # interpreter embedded fallback — run directly
        exec(compile(open(tmp.name).read(), tmp.name, "exec"))

    os.unlink(tmp.name)

if __name__ == "__main__":
    main()
'''

    launcher_path    = os.path.join(tmp_dir, f"{app_name}_launcher.py")
    interpreter_dest = os.path.join(tmp_dir, "interpreter.py")

    with open(launcher_path, 'w', encoding='utf-8') as f:
        f.write(launcher_src)
    shutil.copy(INTERPRETER, interpreter_dest)

    # also copy packages folder if exists
    pkg_dir = os.path.join(NETCH_DIR, "packages")
    if os.path.exists(pkg_dir):
        shutil.copytree(pkg_dir, os.path.join(tmp_dir, "packages"),
                        dirs_exist_ok=True)

    # copy any local assets (same folder as .ntch)
    ntch_dir = os.path.dirname(abs_ntch)
    for f in os.listdir(ntch_dir):
        src_f = os.path.join(ntch_dir, f)
        if os.path.isfile(src_f) and f != os.path.basename(abs_ntch):
            try: shutil.copy(src_f, tmp_dir)
            except: pass

    # build PyInstaller command
    print("  🔨  Compiling with PyInstaller...")
    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--name",     app_name,
        "--distpath", out_dir,
        "--workpath", os.path.join(tmp_dir, "build"),
        "--specpath", tmp_dir,
        "--add-data", f"{interpreter_dest}{os.pathsep}.",
        "--clean",
        "--noconfirm",
        "--log-level", "WARN",
    ]

    if onefile:
        cmd.append("--onefile")
        print("  📦  Mode: Single .exe file")
    else:
        cmd.append("--onedir")
        print("  📦  Mode: Folder distribution")

    if icon and os.path.exists(icon):
        cmd += ["--icon", icon]

    # hide console for window apps
    with open(abs_ntch, 'r') as f:
        src = f.read()
    if 'use window' in src or 'display.webpage' in src:
        cmd.append("--noconsole")
        print("  🖼️   Window app detected — hiding console")

    cmd.append(launcher_path)

    result = subprocess.run(cmd, capture_output=True, text=True)

    shutil.rmtree(tmp_dir, ignore_errors=True)

    if result.returncode != 0:
        print("\n  ❌  Compilation failed!")
        print(result.stdout[-2000:] if result.stdout else "")
        print(result.stderr[-2000:] if result.stderr else "")
        sys.exit(1)

    exe_path = os.path.join(out_dir, f"{app_name}.exe")
    if os.path.exists(exe_path):
        size_mb = os.path.getsize(exe_path) / 1024 / 1024
        print(f"\n  ✅  Compiled successfully!")
        print(f"  📦  Output: {exe_path}")
        print(f"  📏  Size:   {size_mb:.1f} MB")
        print(f"\n  Share {app_name}.exe — no Python needed to run it!")
    else:
        print(f"\n  ✅  Done! Check: {out_dir}")

    print()

def main():
    parser = argparse.ArgumentParser(
        description="Netch 2 — Compile .ntch to standalone .exe",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  netch compiletoexe myapp.ntch
  netch compiletoexe myapp.ntch --output C:/releases
  netch compiletoexe myapp.ntch --name "My Cool App" --icon myapp.ico
  netch compiletoexe myapp.ntch --folder   (creates a folder instead of single exe)
        """
    )
    parser.add_argument("file",         help="Path to your .ntch script")
    parser.add_argument("--output","-o",help="Output folder (default: dist/ next to your script)")
    parser.add_argument("--name",  "-n",help="App name (default: script filename)")
    parser.add_argument("--icon",  "-i",help="Path to .ico file for the exe icon")
    parser.add_argument("--folder",     action="store_true",
                                        help="Create a folder instead of a single .exe")
    args = parser.parse_args()
    compile_to_exe(args.file, args.output, args.name, args.icon, not args.folder)

if __name__ == "__main__":
    main()
